# -*- coding: utf-8 -*-
"""makemore Part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPuV5yG_qPGezCCVyrgsypX2hpF0eWXf
"""

words = open('names.txt', 'r').read().splitlines()
b = {}
for word in words:
  word_pre_suf = ['<'] + list(word) + [']']
  for i in range(len(word_pre_suf) - 2):
    bigram = word_pre_suf[i] + word_pre_suf[i + 1]
    b[bigram] = b.get(bigram, 0) + 1

b = sorted(b.items(), key=lambda x: x[1], reverse=True)
print(b)

import torch
N = torch.zeros((27, 27), dtype=torch.int32)

sorted_chars = sorted(list(set(''.join(words))))
enumerated = enumerate(sorted_chars)
char_to_idx = {char: idx + 1 for idx, char in enumerated}
char_to_idx['*'] = 0
idx_to_char = {idx: char for char, idx in char_to_idx.items()}


for word in words:
  word = '*' + word + '*'
  for ch1, ch2 in zip(word, word[1:]):
    ix1 = char_to_idx[ch1]
    ix2 = char_to_idx[ch2]
    N[ix1, ix2] += 1

P = N.float()
P = (P + 1) / P.sum(1, keepdims=True)

# Creating and training a neural net
import torch.nn.functional as F
import matplotlib.pyplot as plt
xs = []
ys = []
for word in words:
  work_updated = ['*'] + list(word) + ['*']
  for ch1, ch2 in zip(work_updated, work_updated[1:]):
    ix1 = char_to_idx[ch1]
    ix2 = char_to_idx[ch2]
    xs.append(ix1)
    ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)


x_encoded = F.one_hot(xs, num_classes=27).float()
y_encoded = F.one_hot(ys, num_classes=27).float()


W = torch.randn((27, 27), generator=torch.Generator().manual_seed(2147481317), requires_grad=True)

for i in range(500):
  ## Forward pass
  matmul = x_encoded @ W

  counts = matmul.exp()
  probs = counts /counts.sum(1, keepdim=True)

  arr = torch.arange(len(xs))
  vectorised_loss = -(probs[arr, ys]).log().mean() + 0.01 * (W**2).mean()
  print(f"Loss {vectorised_loss}")

  ## Cross entropy version
  # cross_entropy_loss = F.cross_entropy(x_encoded @ W, ys)
  # print(f"Loss {cross_entropy_loss}")

  # W.grad = None
  # cross_entropy_loss.backward()

  ## Backward pass
  W.grad = None
  vectorised_loss.backward()

  W.data += -5 * W.grad

g = torch.Generator().manual_seed(2147483647)
for i in range(5):
  start_char = '*'
  ix = char_to_idx[start_char]
  out = []
  while True:
    #x_encoded = F.one_hot(torch.tensor([ix]), num_classes=27).float()
    matmul = (W[ix]).reshape(1, -1)
    #print(matmul)
    #print(matmul.shape)
    counts = matmul.exp()
    probs = counts / counts.sum(1, keepdim=True)
    ix = torch.multinomial(probs, num_samples=1, replacement=True, generator=g).item()
    out.append(idx_to_char[ix])
    if ix == 0:
      break
  print(''.join(out))

## Seeding data for a trigram neural net
sorted_chars = sorted(list(set(''.join(words))))
enumerated = enumerate(sorted_chars)
char_to_idx = {char: idx + 1 for idx, char in enumerated}
char_to_idx['*'] = 0
idx_to_char = {idx: char for char, idx in char_to_idx.items()}

sorted_chars.insert(0, '*')
counter = 0
trigram_idx_map = {}
idx_trigram_map = {}
for i in range(len(sorted_chars)):
  for j in range(len(sorted_chars)):
    trigram = sorted_chars[i] + sorted_chars[j]
    trigram_idx_map[trigram] = counter
    idx_trigram_map[counter] = trigram
    counter += 1


print(sorted_chars)
print(trigram_idx_map)
print(idx_trigram_map)

# Creating a training a trigram neural net
import torch.nn.functional as F
xs = []
ys = []
for word in words:
  work_updated = ['*', '*'] + list(word) + ['*', '*']
  for ch1, ch2, ch3 in zip(work_updated, work_updated[1:], work_updated[2:]):
    ix = trigram_idx_map[ch1 + ch2]
    iy = char_to_idx[ch3]
    xs.append(ix)
    ys.append(iy)

xs = torch.tensor(xs)
ys = torch.tensor(ys)


xs_encoded = F.one_hot(xs, num_classes=729).float()


W = torch.randn((729, 27), generator=torch.Generator().manual_seed(2147481317), requires_grad=True)
print(xs_encoded.shape)
print(W.shape)

## Gradient descent on trigram neural net

for i in range(500):
  ## Forward pass


  # counts_arr = []
  # for x in xs:
  #   count_row = W[x]
  #   counts_arr.append(count_row)
  # counts_tensor = torch.stack(counts_arr)


  # matmul = xs_encoded @ W

  # counts = matmul.exp()
  # probs = counts /counts.sum(1, keepdim=True)

  # arr = torch.arange(len(xs))
  # vectorised_loss = -(probs[arr, ys]).log().mean() + 0.01 * (W**2).mean()
  # print(f"Loss {vectorised_loss}")

  # Cross entropy version
  cross_entropy_loss = F.cross_entropy(xs_encoded @ W, ys) + 0.01 * (W**2).mean()
  print(f"Loss {cross_entropy_loss}")

  W.grad = None
  cross_entropy_loss.backward()

  ## Backward pass
  # W.grad = None
  # vectorised_loss.backward()

  W.data += -10 * W.grad

# Name generation using trigram neural net
g = torch.Generator().manual_seed(2147481317)
for i in range(50):
  prev_char = '*'
  ix = trigram_idx_map['*' + prev_char]
  out = []
  while True:
    #x_encoded = F.one_hot(torch.tensor([ix]), num_classes=27).float()
    matmul = (W[ix]).reshape(1, -1)
    #print(matmul)
    #print(matmul.shape)
    counts = matmul.exp()
    probs = counts / counts.sum(1, keepdim=True)
    next_char_idx = torch.multinomial(probs, num_samples=1, replacement=True, generator=g).item()
    next_char = idx_to_char[next_char_idx]
    ix = trigram_idx_map[prev_char + next_char]
    prev_char = next_char
    out.append(next_char)
    if next_char == '*':
      break
  print(''.join(out))