# -*- coding: utf-8 -*-
"""makemore mlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BE-PzanzhAJEBzDwDwGy7zFyYDWBM_Z-
"""

import torch.nn.functional as F
import matplotlib.pyplot as plt
import torch


words = open('names.txt', 'r').read().splitlines()

sorted_chars = sorted(list(set(''.join(words))))
enumerated = enumerate(sorted_chars)
char_to_idx = {char: idx + 1 for idx, char in enumerated}
char_to_idx['.'] = 0
idx_to_char = {idx: char for char, idx in char_to_idx.items()}

print(char_to_idx)
print(idx_to_char)

a = torch.randn(1,2,3,4)
b = a.transpose(1, 2)

print(b.shape)
c = a.view(1,3,2,4)

print(c.shape)

print(torch.equal(b, c))

print(c.storage())

print(b.storage())

ix = torch.randint(0, X.shape[0], (32,))
print(ix.shape)
print(ix)


print(X.shape[0])

import random
def construct_dataset(words, block_size):
  X, Y = [], []
  for word in words:
    context = [0] * block_size
    for ch in word + '.':
      X.append(context)
      idx = char_to_idx[ch]
      Y.append(idx)
      context = context[1:] + [idx]
  return torch.tensor(X), torch.tensor(Y)

random.seed(42)
random.shuffle(words)
num_words = len(words)
training_size = int(0.8 * num_words)
validation_size = int(0.1 * num_words)
test_size = num_words - training_size - validation_size
block_size = 5

X_train, Y_train = construct_dataset(words[:training_size], block_size)
X_val, Y_val = construct_dataset(words[training_size:training_size + validation_size], block_size)
X_test, Y_test = construct_dataset(words[training_size + validation_size:], block_size)

print(X_train.shape, Y_train.shape)
print(X_val.shape, Y_val.shape)
print(X_test.shape, Y_test.shape)

g = torch.Generator().manual_seed(2147483647)

embedding_dimension = 5
C = torch.randn((27, embedding_dimension), generator=g)
embeddings = C[X_train]

mat_dimension = block_size * embedding_dimension
invisible_layer_dimension = 300

W1 = torch.randn(mat_dimension, invisible_layer_dimension, generator=g)
b1 = torch.randn(invisible_layer_dimension, generator=g)
h = torch.tanh(embeddings.view(-1, mat_dimension) @ W1 + b1)

W2 = torch.randn((invisible_layer_dimension, 27), generator=g)
b2 = torch.randn(27, generator=g)

parameters = [C, W1, b1, W2, b2]
num_params = [sum(p.nelement() for p in parameters)]
print(num_params)
for p in parameters:
  p.requires_grad = True

sample_size = 50
step = []
loss_values = []
for i in range(200000):
  ## sample random entries from dataset

  ix = torch.randint(0, X_train.shape[0], (sample_size,))

  emb = C[X_train[ix]]
  h = torch.tanh(emb.view(-1, mat_dimension) @ W1 + b1)
  logits = h @ W2 + b2
  loss = F.cross_entropy(logits, Y_train[ix])
  print(loss.item())

  for p in parameters:
    p.grad = None
  loss.backward()

  learning_rate = 0.1 if i < 100000 else 0.01

  for p in parameters:
    p.data += -learning_rate * p.grad

  step.append(i)
  loss_values.append(loss.log10().item())

plt.plot(step, loss_values)
plt.show()

emb = C[X_val]
h = torch.tanh(emb.view(-1, mat_dimension) @ W1 + b1)
logits = h @ W2 + b2
loss = F.cross_entropy(logits, Y_val)
print(loss.item())

emb = C[X_train]
h = torch.tanh(emb.view(-1, mat_dimension) @ W1 + b1)
logits = h @ W2 + b2
loss = F.cross_entropy(logits, Y_train)
print(loss.item())

emb = C[X_test]
h = torch.tanh(emb.view(-1, mat_dimension) @ W1 + b1)
logits = h @ W2 + b2
loss = F.cross_entropy(logits, Y_test)
print(loss.item())

g = torch.Generator().manual_seed(2147483647 + 10)
for i in range(10):
  context = [0] * block_size
  word_idx = []
  while True:
    embedding = C[torch.tensor([context])]
    h = torch.tanh(embedding.view(1, -1) @ W1 + b1)
    logits = h @ W2 + b2
    probs = F.softmax(logits, dim=1)
    ix = torch.multinomial(probs, num_samples=1, replacement=True, generator=g).item()
    word_idx.append(ix)
    context = context[1:] + [ix]
    if ix == 0:
      break
  print(''.join(idx_to_char[i] for i in word_idx))